[features]
seeds = true
skip-lint = false

[programs.localnet]
multisig = "3SunHKjBFnPm9XJn5qqeR9M4janhCexwfJkg5jBnRc2P"

[programs.mainnet]
multisig = "3SunHKjBFnPm9XJn5qqeR9M4janhCexwfJkg5jBnRc2P"

[programs.devnet]
multisig = "3SunHKjBFnPm9XJn5qqeR9M4janhCexwfJkg5jBnRc2P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/hung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
events="yarn run ts-node -r tsconfig-paths/register -r dotenv/config scripts/events-listener.ts"
integration="yarn run ts-node -r tsconfig-paths/register -r dotenv/config scripts/integration.ts"

